-- AlterTable
ALTER TABLE "students" ADD COLUMN     "algebra1_grade" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "college_enroll" TEXT,
ADD COLUMN     "entry_date" DATE,
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "geometry_grade" TEXT,
ADD COLUMN     "hs_gpa" DECIMAL(4,2),
ADD COLUMN     "hs_graduation_year" INTEGER,
ADD COLUMN     "income" TEXT,
ADD COLUMN     "internship_status" TEXT,
ADD COLUMN     "interview_college_score" INTEGER,
ADD COLUMN     "interview_passion_score" INTEGER,
ADD COLUMN     "interview_score" DECIMAL(5,2),
ADD COLUMN     "launchpad_email" TEXT,
ADD COLUMN     "major" TEXT,
ADD COLUMN     "parental_ed" TEXT,
ADD COLUMN     "race_ethnicity" TEXT,
ADD COLUMN     "school_name" TEXT,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "tech_interest_onboarding" INTEGER,
ADD COLUMN     "university" TEXT,
ADD COLUMN     "withdrawal_code" TEXT,
ADD COLUMN     "withdrawal_date" DATE,
ADD COLUMN     "workforce_program_referral" TEXT,
ADD COLUMN     "workforce_referral_status" TEXT,
ADD COLUMN     "zip" TEXT;
